name = "visa-acceptance-toolkit"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Build configuration
[build]
command = "npm run build"

# Environment variables (non-sensitive only)
[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }

# For sensitive environment variables (API keys), use:
# wrangler pages secret put <KEY_NAME>
# or set them in the Cloudflare dashboard
